import RouteLinkedList from "./src/lib/routeLinkedList";
import { Jobs } from "./src/database/job";
const r1 = new RouteLinkedList();

r1.add(Jobs.무도가);
r1.tail.adjustJobPoint(2);
r1.tail.adjustJobPoint(1);
r1.tail.adjustJobPoint(97);
r1.add(Jobs.투사);
r1.removeAt(2);
r1.add(Jobs.검사);
r1.tail.adjustJobPoint(100);
r1.add(Jobs.검객);
r1.tail.adjustJobPoint(100);
r1.add(Jobs.순수마법사);
r1.tail.adjustJobPoint(100);
r1.get(3).adjustJobPoint(-50);
r1.get(3).adjustJobPoint(50);
r1.add(Jobs.모험가);
r1.tail.adjustJobPoint(30);
r1.add(Jobs.빛의기사);
r1.tail.adjustJobPoint(100);
r1.add(Jobs.탐색가);
r1.tail.adjustJobPoint(100);
r1.add(Jobs.순수기사);
r1.tail.adjustJobPoint(100);
console.log(r1);
